name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-kfp:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push for KFP
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile_kfp
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scheduleyoinker
